routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


/*Routes Start for Admin*/
Route::group(['middleware' => ['auth'], 'as'=>'admin.'], function(){
    Route::post('/home/product', 'HomeController@get_home_products')->name('get_home_products');
    Route::post('home/transaction', 'HomeController@get_product_transaction')->name('get_product_transaction');

    //route start for pos user access
    Route::group(['prefix' => 'pos'], function() {
        Route::group(['middleware' => 'auth', 'as'=>'pos.'], function() {
            Route::get('/', 'SellController@get_pos_view')->name('get_pos_view');
            Route::get('/stock/products', 'SellController@get_stock_products')->name('stock_products');
            Route::get('/sold', 'SellController@get_sold_view')->name('get_sold_view');
            Route::get('/sold/details/{id}', 'SellController@get_pos_details')->name('get_pos_details');
            Route::post('/', 'SellController@make_new_sell');
            Route::post('/payment', 'SellController@make_new_payment')->name('make_new_payment');
            Route::post('/return', 'SellController@make_new_return')->name('make_new_return');
            Route::get('/download/{id}', 'SellController@get_invoice_download')->name('get_invoice_download');
            Route::get('/print/{id}', 'SellController@get_invoice_print')->name('get_invoice_print');
        });


        //route start for return  user access
        /*Those Routes for return product*/
        Route::group(['prefix' => 'return', 'as'=>'return.'], function() {
            Route::get('/details/{return_id}', 'ReturnController@get_return_details')->name('get_return_details');
            Route::post('/', 'ReturnController@get_return_product');
            Route::get('/', 'ReturnController@get_return_history')->name('get_return_history');
        });
        //route end for return  user access

        /*those route for transaction*/
        Route::group(['prefix' => 'transaction', 'as'=>'transaction.'], function() {
            Route::post('import', 'TransactionController@import_item')->name('import_item');
            Route::post('details/product', 'TransactionController@get_product_transaction')->name('get_product_transaction');
            Route::post('details/customer', 'TransactionController@get_customer_transaction')->name('get_customer_transaction');
            Route::post('details/brand', 'TransactionController@get_brand_transaction')->name('get_brand_transaction');
            Route::post('details/vendor', 'TransactionController@get_vendor_transaction')->name('get_vendor_transaction');
            Route::post('details/warehouse', 'TransactionController@get_warehouse_transaction')->name('get_warehouse_transaction');

        });
        /*transaction route end*/
    });
    //route end for pos user access

    //route start for inventory  user access
    /*Those Routes for Inventory item*/
    Route::group(['prefix' => 'inventory'], function() {
        Route::group(['as'=>'inventory.'], function() {
            Route::get('/', 'ItemController@get_item_list')->name('get_item_list');
            Route::get('/excel', 'ItemController@download_excel_file')->name('excel');
            Route::post('/product', 'ItemController@get_product_streaming')->name('get_product_streaming');

            Route::post('/item/details', 'ItemController@get_item_details')->name('get_item_details');
            Route::post('/item/update', 'ItemController@update_item')->name('update_item');
            Route::post('/item/delete', 'ItemController@delete_item')->name('delete_item');
            Route::post('/item/info', 'ItemController@get_item_info')->name('get_item_info');

            Route::post('/get_sub_category', 'ItemController@get_sub_category')->name('get_sub_category');
            Route::post('/', 'ItemController@make_new_item');
            Route::get('/category', 'ItemController@get_category_list')->name('get_category_list');
            Route::post('/category', 'ItemController@make_category');
            Route::post('/category/update', 'ItemController@update_category')->name('update_category');
            Route::post('/category/delete', 'ItemController@delete_category')->name('delete_category');
            Route::get('/sub-category', 'ItemController@get_sub_category_list')->name('get_sub_category_list');
            Route::post('/sub-category', 'ItemController@insert_sub_category');
            Route::post('/sub-category/update', 'ItemController@update_sub_category')->name('update_sub_category');

        });
        //those route for excel operations
        Route::group(['prefix' => 'excel', 'as'=>'excel.'], function() {
            Route::get('/category', 'ExcelController@get_category_sheet')->name('category_sheet');
            Route::post('/category', 'ExcelController@import_category_sheet');
            Route::get('/sub-category', 'ExcelController@get_sub_category_sheet')->name('sub_category_sheet');
            Route::post('/sub-category', 'ExcelController@import_sub_category_sheet');

            Route::post('/product', 'ExcelController@import_product_sheet')->name('product_sheet');
        });

    });
    //route end for inventory  user access

    //route start for quotation  user access
    /*Those Routes for Quotation*/
    Route::group(['prefix' => 'quotation', 'as'=>'quotation.'], function() {
        Route::get('/', 'QuotationController@get_quotation_view')->name('get_quotation_view');
        Route::get('/view/{id}', 'QuotationController@get_quotation_details')->name('get_quotation_details');
        Route::get('/download/{id}', 'QuotationController@get_quotation_pdf_download')->name('get_quotation_pdf_download');
        Route::get('/puserrint/{id}', 'QuotationController@get_quotation_print')->name('get_quotation_print');

        Route::get('/make', 'QuotationController@get_new_quotation_view')->name('make_quotation');

        Route::post('/make', 'QuotationController@make_quotation');
    });
    //route end for quotation  user access

    //route start for setting  user access
    //new user with role
    Route::group(['prefix' => 'setting', 'as'=>'user.'], function() {
        Route::get('/', 'UserRoleController@get_user_view')->name('new_user');
        Route::get('/list', 'UserRoleController@get_user_list')->name('user');
        Route::post('/list', 'UserRoleController@update_user_view')->name('user');
        Route::post('/update', 'UserRoleController@update_user_info')->name('user_update');
        Route::post('/details', 'UserRoleController@get_user_view');
        Route::post('/', 'UserRoleController@set_new_user');
        Route::post('/delete', 'UserRoleController@delete_user')->name('delete_user');
        Route::get('/pdf', 'PDFController@get_pdf_setting_view')->name('pdf_setting');
        Route::post('/pdf', 'PDFController@pdf_setting');
    });
    //route end for setting  user access

    //route start for vendor  user access
    /*Those Routes for Vendor*/
    Route::group(['prefix' => 'vendor', 'as'=>'vendor.'], function() {

        Route::get('/', 'VendorController@get_vendor_list')->name('get_vendor_list');
        Route::post('/', 'VendorController@make_vendor');
        Route::post('/update', 'VendorController@update_vendor')->name('update_vendor');
        Route::post('/delete', 'VendorController@delete_vendor')->name('delete_vendor');

    });
    //route end for vendor  user access

    //route start for customer  user access
    /*Those Routes for Customer*/
    Route::group(['prefix' => 'customer', 'as'=>'customer.'], function() {
        Route::get('/', 'CustomerController@get_customer_list')->name('get_customer_list');
        Route::post('/', 'CustomerController@make_customer');
        Route::post('/update', 'CustomerController@update_customer')->name('update_customer');
        Route::post('/delete', 'CustomerController@delete_customer')->name('delete_customer');
    });
    //route end for customer user access

    //route start for warehouse  user access
    /*Those Routes for Warehouse*/
    Route::group(['prefix' => 'warehouse', 'as'=>'warehouse.'], function() {
        Route::get('/', 'WarehouseController@get_warehouse_list')->name('get_warehouse_list');
        Route::get('/transfer', 'WarehouseController@warehouse_transfer')->name('warehouse_transfer');
        Route::get('/transfer/log', 'WarehouseController@warehouse_transfer_log')->name('warehouse_transfer_log');
        Route::post('/transfer', 'WarehouseController@transfer_warehouse_stock');
        Route::post('/qty', 'WarehouseController@warehouse_product_qty')->name('warehouse_product_qty');
        Route::post('/', 'WarehouseController@make_warehouse');
        Route::post('/update', 'WarehouseController@update_warehouse')->name('update_warehouse');
        Route::post('/delete', 'WarehouseController@delete_warehouse')->name('delete_warehouse');
    });
    //route endfor for warehouse  user access

    //route start for brand  user access
    /*Those Routes for Brand*/
    Route::group(['prefix' => 'brand', 'as'=>'brand.'], function() {
        Route::get('/', 'BrandController@get_brand_view')->name('get_brand_view');
        Route::post('/', 'BrandController@make_brand');
        Route::post('/update', 'BrandController@update_brand')->name('update_brand');
        Route::post('/delete', 'BrandController@delete_brand')->name('delete_brand');
    });

resources/views/admin/include/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
       Inventory Project
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {{date('Y')}} <a href="https://winnerdevs.com/">WinnerDevs</a>.</strong> All rights reserved.
</footer>

<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

resources/views/admin/include/header.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('assets/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('assets/css/ionicons.min.css')}}">
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('assets/css/select2.min.css')}}">
<!-- Data Table -->
<link rel="stylesheet" href="{{asset('assets/css/jquery.dataTables.min.css')}}">
<!-- Data Table -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap-timepicker.min.css')}}">
<!-- Datepicker -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap-datepicker.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('assets/css/AdminLTE.min.css')}}">
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
      page. However, you can choose any other skin. Make sure you
      apply the skin class to the body tag so the changes take effect. -->
<link rel="stylesheet" href="{{asset('assets/css/_all-skins.min.css')}}">
<!-- Custom style -->
<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
{{--icon--}}
<link rel="icon" type="image/png" href="{{asset('assets/img/logo.png')}}"/>

resources/views/admin/include/javascript_bar.blade.php
<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('assets/js/select2.full.min.js')}}"></script>
<!-- DataTables -->
<script src="{{asset('assets/js/jquery.dataTables.min.js')}}"></script>
<!-- Timepicker -->
<script src="{{asset('assets/js/bootstrap-timepicker.min.js')}}"></script>
<!-- Datepicker -->
<script src="{{asset('assets/js/bootstrap-datepicker.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('assets/js/adminlte.min.js')}}"></script>
<!-- DC custom -->
<script src="{{asset('assets/js/custom.js')}}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->

resources/views/admin/include/left_sidebar.blade.php
@php
    function has_access($route){
        $roleData = App\UserRole::where(['user_id'=>auth()->user()->getAuthIdentifier()])->select('role')->get();
        foreach ($roleData as $role){
             if(strpos(parse_url(route($route),PHP_URL_PATH), $role->role) !== false){
                return true;
            }
        }
        return false;
    }

@endphp
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        {{--<div class="user-panel">
            <div class="pull-left image">
                <img src="{{asset('assets/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Head Admin</p>
                <!-- Status -->
                <a href="javascript:void(0);"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>--}}

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <!--<li class="header">HEADER</li>->
        <!-- Optionally, you can add icons to the links -->
            <li @if(URL::current()==route('home')) class="active" @endif>
                <a href="{{route('home')}}">
                    <i class="fa fa-home" aria-hidden="true"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
            </span>
                </a>
            </li>
            @if(has_access('admin.pos.get_pos_view'))
                <li @if(URL::current()==route('admin.pos.get_pos_view')) class="active" @endif>
                    <a href="{{route('admin.pos.get_pos_view')}}">
                        <i class="fa fa-cart-arrow-down" aria-hidden="true"></i> <span>POS</span>

                    </a>
                </li>
            @endif
            @if(has_access('admin.inventory.get_item_list'))
            <li @if(strpos(URL::current(), route('admin.inventory.get_item_list')) !== false)  class="active treeview" @else
            class="treeview" @endif>
                <a href="javascript:void(0);">
                    <i class="fa fa-suitcase" aria-hidden="true"></i> <span>Inventory</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul  class="treeview-menu">
                    <li @if(URL::current()==route('admin.inventory.get_item_list'))  class="active" @endif>
                        <a href="{{route('admin.inventory.get_item_list')}}"><i class="fa fa-circle-o"></i> Item List </a>
                    </li>
                    <li @if(URL::current()==route('admin.inventory.get_category_list'))  class="active" @endif>
                        <a href="{{route('admin.inventory.get_category_list')}}"><i class="fa fa-circle-o"></i> Category List </a>
                    </li>
                    <li @if(URL::current()==route('admin.inventory.get_sub_category_list'))  class="active" @endif>
                        <a href="{{route('admin.inventory.get_sub_category_list')}}"><i class="fa fa-circle-o"></i> Sub-Category List </a>
                    </li>
                </ul>
            </li>
            @endif
            @if(has_access('admin.pos.get_sold_view'))
            <li @if(URL::current()==route('admin.pos.get_sold_view')) class="active" @endif>
                <a href="{{route('admin.pos.get_sold_view')}}">
                    <i class="fa fa-list" aria-hidden="true"></i> <span>Sold List</span>

                </a>
            </li>
            @endif

            @if(has_access('admin.warehouse.get_warehouse_list'))
                <li @if(strpos(URL::current(), route('admin.warehouse.get_warehouse_list')) !== false)  class="active
                treeview" @else class="treeview" @endif>
                    <a href="javascript:void(0);">
                        <i class="fa fa-bank" aria-hidden="true"></i> <span>Warehouse</span>
                        <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                    </a>
                    <ul class="treeview-menu">
                        <li  @if(URL::current()==route('admin.warehouse.get_warehouse_list'))  class="active" @endif>
                            <a href="{{route('admin.warehouse.get_warehouse_list')}}"><i class="fa fa-circle-o"></i> Warehouse List </a>
                        </li>
                        <li  @if(URL::current()==route('admin.warehouse.warehouse_transfer'))  class="active" @endif>
                            <a href="{{route('admin.warehouse.warehouse_transfer')}}"><i class="fa fa-circle-o"></i> Warehouse Transfer </a>
                        </li>
                        <li  @if(URL::current()==route('admin.warehouse.warehouse_transfer_log'))  class="active"
                                @endif>
                            <a href="{{route('admin.warehouse.warehouse_transfer_log')}}"><i class="fa
                            fa-circle-o"></i> Warehouse Transfer Log</a>
                        </li>
                    </ul>
                </li>
            @endif
            @if(has_access('admin.brand.get_brand_view'))
                <li @if(URL::current()==route('admin.brand.get_brand_view')) class="active" @endif>
                    <a href="{{route('admin.brand.get_brand_view')}}">
                        <i class="fa fa-codepen" aria-hidden="true"></i> <span>Brand</span>
                    </a>
                </li>
            @endif
            @if(has_access('admin.vendor.get_vendor_list'))
                <li @if(strpos(URL::current(), route('admin.vendor.get_vendor_list')) !== false)  class="active
                treeview" @else class="treeview" @endif>
                    <a href="javascript:void(0);">
                        <i class="fa fa-user" aria-hidden="true"></i> <span>Vendor</span>
                        <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                    </a>
                    <ul class="treeview-menu">
                        <li @if(URL::current()==route('admin.vendor.get_vendor_list'))  class="active" @endif>
                            <a href="{{route('admin.vendor.get_vendor_list')}}"><i class="fa fa-circle-o"></i> Vendors List </a>
                        </li>
                    </ul>
                </li>
            @endif
            @if(has_access('admin.customer.get_customer_list'))
                <li @if(strpos(URL::current(), route('admin.customer.get_customer_list')) !== false)  class="active
                treeview" @else class="treeview" @endif>
                    <a href="javascript:void(0);">
                        <i class="fa fa-users" aria-hidden="true"></i> <span>Customers</span>
                        <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                    </a>
                    <ul class="treeview-menu">
                        <li @if(URL::current()==route('admin.customer.get_customer_list'))  class="active" @endif>
                            <a href="{{route('admin.customer.get_customer_list')}}"><i class="fa fa-circle-o"></i> Customers List</a>
                        </li>
                    </ul>
                </li>
            @endif
            @if(has_access('admin.quotation.get_quotation_view'))
                <li @if(strpos(URL::current(), route('admin.quotation.get_quotation_view')) !== false)  class="active
                treeview" @else class="treeview" @endif>
                    <a href="javascript:void(0);">
                        <i class="fa fa-dollar" aria-hidden="true"></i> <span>Quotation</span>
                        <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
                    </a>
                    <ul class="treeview-menu">
                        <li @if(URL::current()==route('admin.quotation.make_quotation'))  class="active" @endif>
                            <a href="{{route('admin.quotation.make_quotation')}}"><i class="fa fa-circle-o"></i> New Quotation </a></li>
                        <li @if(URL::current()==route('admin.quotation.get_quotation_view'))  class="active" @endif>
                            <a href="{{route('admin.quotation.get_quotation_view')}}"><i class="fa fa-circle-o"></i>Quotation List </a></li>
                    </ul>
                </li>
            @endif
            @if(has_access('admin.user.new_user'))
            <li @if(strpos(URL::current(), route('admin.user.new_user')) !== false)  class="active
            treeview" @else class="treeview" @endif>
                <a href="javascript:void(0);">
                    <i class="fa fa-sliders" aria-hidden="true"></i> <span>Settings</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li @if(URL::current()==route('admin.user.new_user'))  class="active" @endif>
                        <a href="{{route('admin.user.new_user')}}"><i class="fa fa-circle-o"></i> New User </a></li>
                    <li @if(URL::current()==route('admin.user.user'))  class="active" @endif>
                        <a href="{{route('admin.user.user')}}"><i class="fa fa-circle-o"></i>User List </a></li>
                    <li @if(URL::current()==route('admin.user.pdf_setting'))  class="active" @endif>
                        <a href="{{route('admin.user.pdf_setting')}}"><i class="fa fa-circle-o"></i>PDF
                            Setting</a></li>
                </ul>
            </li>
            @endif
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/admin/include/top_sidebar.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{url('/')}}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>N</b>AB</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>N</b>AB</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                                <!-- end notification -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- Tasks Menu -->

                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{asset('assets/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{auth()->user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{asset('assets/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <div class="pull-right">
                                    <a class="btn btn-default btn-flat" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->